### ISSUE TITLE
Upgrade to Joi 17

### ISSUE THREAD

**Issue by ealbuquerque** [dszakallas/joi-extension-semver#29]
For maintain a longevity of the library, we could update the version of `@hapi/joi` to `17.x.x`.

\õ/

**Comment by paulmelnikow** [comment]
For reference, there was some discussion about this here: https://github.com/dszakallas/joi-extension-semver/pull/19#issuecomment-629437473

I poked at this a bit. Since Joi is a peer dep, it's not getting installed by joi-extension-semver, rather it should use the version you install. This package declares a peer dependency on >=16.0, so there's no reason that shouldn't resolve to 17.x if that's what you have installed.

https://github.com/dszakallas/joi-extension-semver/blob/35f9c244f17837bc26ad35ee58e7042de3b99892/package.json#L35

Is this replicable in your test project? Does the same issue happen with npm or only with yarn?

**Comment by ealbuquerque** [comment]
@paulmelnikow, doing some tests it only happens when I do it with the `joi-extension-semver` local project with `yarn link` or `npm link`

I did some tests with versions `joi-extension-semver@4.0.0` and `joi-extension-semver@4.1.0` and it worked fine.

My test project, if you want to test: https://github.com/ealbuquerque/typescript-joi-semver/tree/error-02

I think this task can be closed.

**Comment by ealbuquerque** [comment]
I found it very strange that this happens only when I link the local project. I couldn't find any other reason.

Before opening the task I didn't pay attention to testing it without the local link. Sorry, man.

**Comment by paulmelnikow** [comment]
No problem! Glad it's working. Yea, `yarn link` / `npm link` are notorious for creating issues like this.
